# Generated by Django 2.1.8 on 2019-07-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ding',
            name='alias',
            field=models.CharField(db_index=True, default='a', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
